# Generated by Django 3.1 on 2020-10-26 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=250, null=True)),
                ('in_restaurant', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('customer', models.ForeignKey(db_column='customer', on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
