# Generated by Django 3.1 on 2020-11-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=80)),
                ('cardnumber', models.CharField(max_length=16)),
                ('zip', models.CharField(max_length=10)),
                ('expiration', models.CharField(max_length=10)),
                ('securitycode', models.CharField(max_length=4)),
            ],
        ),
    ]
