# Generated by Django 3.1 on 2020-11-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='low_contact',
            field=models.BooleanField(default=False),
        ),
    ]
