# Generated by Django 3.1 on 2020-11-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busser_supplies_requests',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
