# Generated by Django 3.1 on 2020-11-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busser', '0002_busser_supplies_requests_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1'), ('A2', 'A2'), ('B2', 'B2'), ('C2', 'C2'), ('A3', 'A3'), ('B3', 'B3'), ('C3', 'C3')], max_length=255)),
                ('table', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)])),
                ('seats', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)])),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Dirty', 'Dirty'), ('Closed', 'Closed'), ('Reserved', 'Reserved')], max_length=255)),
            ],
        ),
    ]
