# Generated by Django 3.1 on 2020-10-17 18:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tableTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableName', models.CharField(default='A1', max_length=10)),
                ('seats', models.IntegerField()),
                ('tableType', models.CharField(choices=[('bar', 'bar'), ('booth', 'booth'), ('table', 'table'), ('hi-top', 'hi-top'), ('patio', 'patio')], max_length=255)),
                ('status', models.CharField(choices=[('cleaned', 'cleaned'), ('seated', 'seated'), ('closed', 'closed'), ('reserved', 'reserved')], max_length=255)),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guestName', models.CharField(max_length=25)),
                ('guestCount', models.IntegerField(default=1)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tabletable')),
            ],
        ),
    ]
