# Generated by Django 3.1 on 2020-11-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201022_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletable',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('occupied', 'occupied'), ('closed', 'closed'), ('reserved', 'reserved')], max_length=255),
        ),
    ]
