# Generated by Django 3.1 on 2020-11-10 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0002_auto_20201110_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplyorder',
            name='quantity',
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ingredient', models.ForeignKey(db_column='ingredient', on_delete=django.db.models.deletion.CASCADE, to='chef.supplyorder')),
            ],
        ),
    ]
