# Generated by Django 3.1 on 2020-11-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0005_auto_20201110_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyorder',
            name='status',
            field=models.CharField(choices=[('On Order', 'On Order'), ('Ordered', 'Ordered'), ('Received', 'Received')], default='On Order', max_length=20),
        ),
    ]
