# Generated by Django 3.1 on 2020-11-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Server_Section',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
