# Generated by Django 3.1 on 2020-11-04 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_auto_20201021_1505'),
        ('customer', '0006_payment'),
        ('home', '0003_auto_20201022_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderstable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordertype', models.CharField(choices=[('dine-in', 'dine-in'), ('carryout', 'carryout'), ('delivery', 'delivery')], default='dine-in', max_length=10)),
                ('status', models.CharField(blank=True, choices=[('needDrinks', 'Needs Drinks'), ('needToOrder', 'Needs to Order'), ('orderTaken', 'Order Taken'), ('sentToKitchen', 'Sent To Kitchen'), ('sentBacktoServer', 'Sent to Server'), ('orderCompleted', 'Order Completed'), ('delivered', 'Delivered')], default='orderTaken', max_length=255, null=True)),
                ('timeordered', models.DateTimeField(auto_now=True, null=True)),
                ('timecompleted', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('paid', models.BooleanField(choices=[(True, 'Paid'), (False, 'Not_Paid')], default=False)),
                ('requestedtime', models.DateTimeField(auto_now=True, null=True)),
                ('customername', models.ForeignKey(db_column='customername', on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('tablenumber', models.ForeignKey(blank=True, db_column='tablenumber', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.tabletable')),
            ],
        ),
        migrations.CreateModel(
            name='Itemtable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialinstructions', models.CharField(blank=True, max_length=255, null=True)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('server', models.CharField(blank=True, max_length=255, null=True)),
                ('ordertime', models.DateTimeField(blank=True, null=True)),
                ('completiontime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('waiting', 'waiting'), ('preparing', 'preparing'), ('completed', 'completed'), ('delivered', 'delivered')], max_length=255, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('menuitem', models.ForeignKey(db_column='menuitem', default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.menu_item')),
                ('ordernumber', models.ForeignKey(db_column='ordernumber', on_delete=django.db.models.deletion.CASCADE, to='tickets.orderstable')),
            ],
        ),
    ]
