# Generated by Django 3.1 on 2020-11-04 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstable',
            name='requestedtime',
        ),
    ]
