# Generated by Django 3.1 on 2020-11-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20201109_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertstable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=10)),
                ('receiver', models.CharField(max_length=10)),
                ('message', models.CharField(max_length=50)),
                ('time', models.TimeField(auto_now_add=True)),
                ('priority', models.BooleanField(default=False)),
            ],
        ),
    ]
