# Generated by Django 3.1 on 2020-11-01 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_Name', models.CharField(max_length=50)),
                ('item_Category', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense'), ('Other', 'Other')], max_length=50)),
                ('item_Note', models.CharField(default=None, max_length=100)),
                ('item_Date', models.DateField()),
                ('item_Amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
                ('customerName', models.CharField(default=None, max_length=255)),
                ('inRestaurant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule_Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_Name', models.CharField(max_length=50)),
                ('worker_Position', models.CharField(choices=[('Chef', 'Chef'), ('Server', 'Server'), ('Busser', 'Busser'), ('Manager', 'Manager'), ('Host', 'Host'), ('Delivery', 'Delivery')], max_length=50)),
                ('worker_Start', models.TimeField()),
                ('worker_End', models.TimeField()),
                ('worker_Date', models.DateField()),
                ('worker_Break', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker_Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField()),
            ],
        ),
    ]
